name: CI
on: [push]
jobs:
  build:
    name: Build And Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      - name: Archive production artifacts
        uses: papeloto/action-zip@v1
        with:
          name: build-artifacts
          files: dist/
          dest: archived.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: archived.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
